### ISSUE TITLE
Meet Our Team section needs to be a slider, not static cards

### ISSUE THREAD

**Issue by EktaNaik** [chaitanya-ajency/western-capital#16]
**Issue**:

- Currently Meet Our Team is developed as a static section and hence adding more than 4 team members (if needed later) will be an issue.
![image](https://user-images.githubusercontent.com/44566188/122213970-2c2ea400-cec7-11eb-9fa3-e2b17466d0e1.png)

**Required Behavior:**

- The team section should be a slider (with existing card UI) displaying 4 cards at a time. 
- Cards to be center-aligned in the section so UI remains uniform if there are less than 4 cards.
- Also, mobile UI of each member card to be different from desktop since on-hover does not work on mobile.
- For mobile, display the member image followed by description text below the image for each member.
- Ref. - https://www.mockplus.com/ (See Mockplus Cloud section on mobile)-

**Comment by EktaNaik** [comment]
@chaitanya-ajency The transition effect added for this slider on desktop loads 4 team members at a time on scroll. This gives an illusion that next 4 member cards are loading whereas it loads just 1 card and not 4. Can we change this transition effect to animate just 1 slide at a time?

**Required Behaviour/Transition effect:**

- https://justher.in/ - Check the transition effect of "Love from the JustHer Tribe" section.
- Also enable arrows, navigation dots below and auto-scroll for the slider.

**Comment by chaitanya-ajency** [comment]
**Also enable arrows** >> Will not be possible as the tab-pane container is having overflow : hidden; to achieve the working of slider inside Tab 2..

**Comment by EktaNaik** [comment]
Fixed and tested.
