### ISSUE TITLE
Contact Us - Contact icons look blurry

### ISSUE THREAD

**Issue by EktaNaik** [chaitanya-ajency/western-capital#23]
**Issue:**

- Icons added for email, phone number and address details look blurry. 
- See screenshot:
![image](https://user-images.githubusercontent.com/44566188/123252646-2578e000-d50a-11eb-84b3-741fbdc30601.png)

**Comment by chaitanya-ajency** [comment]
3x image taken form design

**Comment by EktaNaik** [comment]
@chaitanya-ajency the icons still look blurry. Issue not fixed. See screenshot.
![image](https://user-images.githubusercontent.com/44566188/123921632-d7019080-d9a4-11eb-9556-701b058c13b9.png)

**Comment by EktaNaik** [comment]
Fixed and tested.
