### ISSUE TITLE
Contact Us - Mark the message field in the form as mandatory

### ISSUE THREAD

**Issue by EktaNaik** [chaitanya-ajency/western-capital#25]
**Issue:**

- The message field is not displayed as a mandatory field in the form, but shows error if you try to submit the form with a blank message field. See screenshot.
![image](https://user-images.githubusercontent.com/44566188/123256487-a6d27180-d50e-11eb-9fd7-80991bde9137.png)

**Required Behavior:**

- Add * to field similar to the other mandatory fields if a field has been set as a mandatory field in the backend.

**Comment by EktaNaik** [comment]
@chaitanya-ajency this issue has not been fixed yet. The "*" is still not added next to the field label. Please check and fix it properly. See screenshot.

![image](https://user-images.githubusercontent.com/44566188/123916661-89365980-d99f-11eb-91d6-ac317f9e0690.png)

**Comment by chaitanya-ajency** [comment]
@EktaNaik The mark was not there in the design hence not put.. I will add it now

**Comment by EktaNaik** [comment]
Fixed and tested.
