### ISSUE TITLE
Regulatory Page - Color of pdf icons used should be Dark Blue (theme color)

### ISSUE THREAD

**Issue by EktaNaik** [chaitanya-ajency/western-capital#40]
**Issue:**

- Wrong colored images have been used for the pdf icons. this needs to be changed to the Dark Blue as per the theme. See screenshot.
![image](https://user-images.githubusercontent.com/44566188/123927433-77a67f00-d9aa-11eb-8382-0ee7c47d53c2.png)

**Comment by chaitanya-ajency** [comment]
Icons changed.. as designer cudnt trace the previous img.. Plz let me know if need to chnge

**Comment by EktaNaik** [comment]
Fixed and tested.
