### ISSUE TITLE
Regulatory Page - Add styling for mouse hover for each policy

### ISSUE THREAD

**Issue by EktaNaik** [chaitanya-ajency/western-capital#41]
**Issue:**

- Add text underline same as that of the header menu tabs for mouse hover on each policy. See screenshot.
- Reference - https://capitalfloat.com/regulatory/
![image](https://user-images.githubusercontent.com/44566188/123929824-cf45ea00-d9ac-11eb-9989-b1c686b9aca2.png)

**Comment by chaitanya-ajency** [comment]
@EktaNaik Cannot achieve the tabs menu effect as in there it is single line and pseudo ::after is used and in the pdf section it is on multiple line hence can only put text-decoration undeline.. Or else the line will com for the text container only

Please let me know if it shud be for only the bottom part or all the lines?

**Comment by EktaNaik** [comment]
Fixed and tested.
